
export var userDetails = [{
    "key": 10,
    "userId": 10,
    "userName": "user2account",
    "ownedCardsCount": 355,
    "ownedCards": [
        21,
        8,
        36,
        44,
        42,
        38,
        75,
        16,
        85,
        62,
        67,
        8,
        89,
        16,
        85,
        62,
        67,
        8,
        89,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        32,
        59,
        40,
        55,
        80,
        63,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        12,
        58,
        80,
        2,
        35,
        98,
        9,
        34,
        0,
        70,
        59,
        3,
        32,
        59,
        40,
        55,
        80,
        63,
        3,
        2,
        14,
        9,
        8,
        3,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        3,
        2,
        14,
        9,
        8,
        3,
        3,
        2,
        14,
        9,
        8,
        3,
        6,
        14,
        1,
        14,
        2,
        14,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        7,
        13,
        8,
        5,
        13,
        11,
        6,
        14,
        1,
        14,
        2,
        14,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        13,
        8,
        5,
        13,
        11,
        15,
        2,
        3,
        4,
        4,
        13,
        14,
        11,
        12,
        2,
        14,
        12,
        15,
        14,
        3,
        4,
        15,
        4,
        6,
        14,
        1,
        14,
        2,
        14,
        6,
        14,
        1,
        14,
        2,
        14,
        4,
        7,
        9,
        1,
        7,
        7,
        7,
        13,
        8,
        5,
        13,
        11,
        7,
        11,
        9,
        12,
        15,
        9,
        6,
        8,
        6,
        9,
        4,
        4,
        3,
        7,
        9,
        8,
        3,
        13,
        3,
        7,
        9,
        8,
        3,
        13,
        8,
        15,
        3,
        12,
        10,
        14,
        15,
        5,
        1,
        2,
        14,
        2
    ],
    "ownedPacksCount": 19,
    "ownedPacks": [
        10,
        21,
        32,
        43,
        54,
        65,
        76,
        87,
        98,
        109,
        120,
        131,
        142,
        153,
        164,
        175,
        186,
        197,
        208
    ],
    "option": ""
}
];

export var packDetails = [
        {
            "key": 10,
            "packId": 10,
            "packType": "Type1",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                8,
                36,
                44,
                42,
                38,
                75
            ]
        },
        {
            "key": 21,
            "packId": 21,
            "packType": "Type2",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                3,
                2,
                14,
                9,
                8,
                3
            ]
        },
        {
            "key": 32,
            "packId": 32,
            "packType": "Type1",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                6,
                14,
                1,
                14,
                2,
                14
            ]
        },
        {
            "key": 43,
            "packId": 43,
            "packType": "Type1",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 54,
            "packId": 54,
            "packType": "Type45",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 65,
            "packId": 65,
            "packType": "20",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 76,
            "packId": 76,
            "packType": "20",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 87,
            "packId": 87,
            "packType": "20",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 98,
            "packId": 98,
            "packType": "23",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 109,
            "packId": 109,
            "packType": "45",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 120,
            "packId": 120,
            "packType": "46",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 131,
            "packId": 131,
            "packType": "47",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                3,
                7,
                9,
                8,
                3,
                13
            ]
        },
        {
            "key": 142,
            "packId": 142,
            "packType": "48",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 153,
            "packId": 153,
            "packType": "49",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 164,
            "packId": 164,
            "packType": "59",
            "owner": "user2account",
            "openedStatus": 0,
            "populatedCards": []
        },
        {
            "key": 175,
            "packId": 175,
            "packType": "58",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                7,
                11,
                9,
                12,
                15,
                9
            ]
        },
        {
            "key": 186,
            "packId": 186,
            "packType": "131",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                6,
                8,
                6,
                9,
                4,
                4
            ]
        },
        {
            "key": 197,
            "packId": 197,
            "packType": "56",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                8,
                15,
                3,
                12,
                10,
                14
            ]
        },
        {
            "key": 208,
            "packId": 208,
            "packType": "undefined",
            "owner": "user2account",
            "openedStatus": 1,
            "populatedCards": [
                15,
                5,
                1,
                2,
                14,
                2
            ]
        }
    ]

export var marketDetails= [
        {
            "key": 10,
            "buyOrderId": 10,
            "status": 1,
            "owner": "user2account",
            "cardId": 21
        },
        {
            "key": 21,
            "buyOrderId": 21,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 32,
            "buyOrderId": 32,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 43,
            "buyOrderId": 43,
            "status": 1,
            "owner": "user2account",
            "cardId": 9
        },
        {
            "key": 54,
            "buyOrderId": 54,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 65,
            "buyOrderId": 65,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 76,
            "buyOrderId": 76,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 87,
            "buyOrderId": 87,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 98,
            "buyOrderId": 98,
            "status": 1,
            "owner": "user2account",
            "cardId": 12
        },
        {
            "key": 109,
            "buyOrderId": 109,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 120,
            "buyOrderId": 120,
            "status": 1,
            "owner": "user2account",
            "cardId": 14
        },
        {
            "key": 131,
            "buyOrderId": 131,
            "status": 1,
            "owner": "user2account",
            "cardId": 10
        },
        {
            "key": 142,
            "buyOrderId": 142,
            "status": 1,
            "owner": "user2account",
            "cardId": 9
        },
        {
            "key": 153,
            "buyOrderId": 153,
            "status": 1,
            "owner": "user2account",
            "cardId": 6
        },
        {
            "key": 164,
            "buyOrderId": 164,
            "status": 1,
            "owner": "user2account",
            "cardId": 1
        },
        {
            "key": 175,
            "buyOrderId": 175,
            "status": 1,
            "owner": "user2account",
            "cardId": 2
        },
        {
            "key": 186,
            "buyOrderId": 186,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 197,
            "buyOrderId": 197,
            "status": 1,
            "owner": "user2account",
            "cardId": 11
        },
        {
            "key": 208,
            "buyOrderId": 208,
            "status": 1,
            "owner": "user2account",
            "cardId": 8
        },
        {
            "key": 219,
            "buyOrderId": 219,
            "status": 1,
            "owner": "user2account",
            "cardId": 9
        },
        {
            "key": 230,
            "buyOrderId": 230,
            "status": 1,
            "owner": "user2account",
            "cardId": 10
        },
        {
            "key": 241,
            "buyOrderId": 241,
            "status": 1,
            "owner": "user2account",
            "cardId": 10
        },
        {
            "key": 252,
            "buyOrderId": 252,
            "status": 1,
            "owner": "user2account",
            "cardId": 2
        },
        {
            "key": 263,
            "buyOrderId": 263,
            "status": 1,
            "owner": "user2account",
            "cardId": 2
        }
    ]