export const TOGGLE_ON_CLICK = 'TOGGLE_ON_CLICK';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_PACK_DATA = 'UPDATE_PACK_DATA';
export const UPDATE_MARKET_DATA = 'UPDATE_MARKET_DATA';